from pathlib import Path

path = Path("cl_st1_gelc_llm_tagger_ptbr/tagset/tagset_ptbr.md")

replacements = {
    "142. pronomes relativos precedidos de preposição:": "21. pronomes relativos precedidos de preposição:",
    "143. quantificadores pronominais ou determinativos:": "22. quantificadores pronominais ou determinativos:",
    "144. pronomes pessoais em posição de sujeito:": "23. pronomes pessoais em posição de sujeito:",
    "145. pronomes de primeira pessoa em posição de sujeito:": "24. pronomes de primeira pessoa em posição de sujeito:",
    "146. pronomes de segunda pessoa em posição de sujeito:": "25. pronomes de segunda pessoa em posição de sujeito:",
    "147. pronomes de terceira pessoa em posição de sujeito:": "26. pronomes de terceira pessoa em posição de sujeito:",

    "21. substantivos próprios:": "27. substantivos próprios:",
    "22. substantivos comuns:": "28. substantivos comuns:",
    "23. substantivos abstratos:": "29. substantivos abstratos:",
    "24. substantivos concretos:": "30. substantivos concretos:",
    "25. substantivos animados:": "31. substantivos animados:",
    "26. substantivos coletivos:": "32. substantivos coletivos:",
    "27. substantivos de quantidade:": "33. substantivos de quantidade:",
    "28. substantivos cognitivos:": "34. substantivos cognitivos:",
    "29. substantivos de processo:": "35. substantivos de processo:",
    "30. substantivos técnicos:": "36. substantivos técnicos:",
    "31. nominalizações:": "37. nominalizações:",
    "148. substantivos de lugar:": "38. substantivos de lugar:",
    "149. substantivos institucionais:": "39. substantivos institucionais:",
    "150. substantivos em posição de sujeito:": "40. substantivos em posição de sujeito:",
    "151. nominalizações em posição de sujeito:": "41. nominalizações em posição de sujeito:",

    "32. adjetivos qualificativos atributivos:": "42. adjetivos qualificativos atributivos:",
    "33. adjetivos qualificativos predicativos:": "43. adjetivos qualificativos predicativos:",
    "34. adjetivos relacionais:": "44. adjetivos relacionais:",
    "35. adjetivos avaliativos:": "45. adjetivos avaliativos:",
    "36. adjetivos de tamanho:": "46. adjetivos de tamanho:",
    "37. adjetivos de idade e tempo:": "47. adjetivos de idade e tempo:",
    "38. adjetivos de cor:": "48. adjetivos de cor:",
    "39. adjetivos de nacionalidade e origem:": "49. adjetivos de nacionalidade e origem:",
    "152. adjetivos atributivos pré-nominais:": "50. adjetivos atributivos pré-nominais:",
    "153. adjetivos atributivos pós-nominais:": "51. adjetivos atributivos pós-nominais:",
    "154. adjetivos superlativos:": "52. adjetivos superlativos:",
    "155. adjetivos tópicos ou temáticos:": "53. adjetivos tópicos ou temáticos:",
    "156. adjetivos exceto avaliativos:": "54. adjetivos exceto avaliativos:",

    "40. verbos lexicais:": "55. verbos lexicais:",
    "41. verbos auxiliares:": "56. verbos auxiliares:",
    "42. verbos copulativos:": "57. verbos copulativos:",
    "43. verbos de comunicação:": "58. verbos de comunicação:",
    "44. verbos cognitivos/mentais:": "59. verbos cognitivos/mentais:",
    "45. verbos de percepção:": "60. verbos de percepção:",
    "46. verbos de movimento:": "61. verbos de movimento:",
    "47. verbos causativos:": "62. verbos causativos:",
    "48. verbos existenciais:": "63. verbos existenciais:",
    "49. verbos aspectuais:": "64. verbos aspectuais:",
    "50. verbos modais e semimodais:": "65. verbos modais e semimodais:",
    "157. verbos de ação/atividade:": "66. verbos de ação/atividade:",
    "158. verbos de ocorrência:": "67. verbos de ocorrência:",
    "159. verbos de facilitação:": "68. verbos de facilitação:",
    "160. verbos privados:": "69. verbos privados:",
    "161. verbos públicos:": "70. verbos públicos:",
    "162. verbos persuasivos/suasivos:": "71. verbos persuasivos/suasivos:",
    "163. verbos de desejo/volição:": "72. verbos de desejo/volição:",
    "164. verbos de probabilidade/aparência:": "73. verbos de probabilidade/aparência:",
    "165. modais de possibilidade:": "74. modais de possibilidade:",
    "166. modais de obrigação:": "75. modais de obrigação:",
    "167. modais de necessidade:": "76. modais de necessidade:",
    "168. modais de capacidade:": "77. modais de capacidade:",
    "169. modais de evidencialidade/aparência:": "78. modais de evidencialidade/aparência:",

    "51. presente do indicativo:": "79. presente do indicativo:",
    "52. pretérito perfeito simples:": "80. pretérito perfeito simples:",
    "53. pretérito imperfeito:": "81. pretérito imperfeito:",
    "54. pretérito mais-que-perfeito simples e composto:": "82. pretérito mais-que-perfeito simples e composto:",
    "55. futuro do presente:": "83. futuro do presente:",
    "56. futuro perifrástico:": "84. futuro perifrástico:",
    "57. futuro do pretérito/condicional:": "85. futuro do pretérito/condicional:",
    "58. imperativo afirmativo:": "86. imperativo afirmativo:",
    "59. imperativo negativo:": "87. imperativo negativo:",
    "60. presente do subjuntivo:": "88. presente do subjuntivo:",
    "61. pretérito imperfeito do subjuntivo:": "89. pretérito imperfeito do subjuntivo:",
    "62. futuro do subjuntivo:": "90. futuro do subjuntivo:",
    "63. aspecto perfeito composto:": "91. aspecto perfeito composto:",
    "64. perífrases progressivas:": "92. perífrases progressivas:",
    "65. perífrases incoativas:": "93. perífrases incoativas:",
    "66. perífrases terminativas:": "94. perífrases terminativas:",
    "67. voz passiva analítica:": "95. voz passiva analítica:",
    "68. voz passiva sintética/pronominal:": "96. voz passiva sintética/pronominal:",
    "69. construções impessoais:": "97. construções impessoais:",
    "170. verbo no infinitivo:": "98. verbo no infinitivo:",
    "171. infinitivo pessoal:": "99. infinitivo pessoal:",
    "172. verbo no gerúndio:": "100. verbo no gerúndio:",
    "173. particípio passado:": "101. particípio passado:",
    "174. modo indicativo:": "102. modo indicativo:",
    "175. passiva analítica com agente:": "103. passiva analítica com agente:",
    "176. passiva analítica sem agente:": "104. passiva analítica sem agente:",
    "177. auxiliares com clivagem por advérbio:": "105. auxiliares com clivagem por advérbio:",

    "70. advérbios de tempo:": "106. advérbios de tempo:",
    "71. advérbios de lugar:": "107. advérbios de lugar:",
    "72. advérbios de modo:": "108. advérbios de modo:",
    "73. advérbios de quantidade/intensidade:": "109. advérbios de quantidade/intensidade:",
    "74. advérbios de afirmação:": "110. advérbios de afirmação:",
    "75. advérbios de negação:": "111. advérbios de negação:",
    "76. advérbios de dúvida/probabilidade:": "112. advérbios de dúvida/probabilidade:",
    "77. advérbios focalizadores:": "113. advérbios focalizadores:",
    "78. advérbios intensificadores/amplificadores:": "114. advérbios intensificadores/amplificadores:",
    "79. advérbios atitudinais:": "115. advérbios atitudinais:",
    "80. advérbios epistêmicos/factivos:": "116. advérbios epistêmicos/factivos:",
    "81. advérbios de mitigação/hedges:": "117. advérbios de mitigação/hedges:",
    "178. advérbio de negação `não`:": "118. advérbio de negação `não`:",
    "179. advérbios negativos exceto `não`:": "119. advérbios negativos exceto `não`:",
    "180. advérbios de probabilidade:": "120. advérbios de probabilidade:",
    "181. advérbios factivos/de certeza:": "121. advérbios factivos/de certeza:",
    "182. advérbios não factuais/evidenciais:": "122. advérbios não factuais/evidenciais:",
    "183. advérbios suavizadores/downtoners:": "123. advérbios suavizadores/downtoners:",
    "184. advérbios enfatizadores:": "124. advérbios enfatizadores:",
    "185. advérbios comparativos:": "125. advérbios comparativos:",
    "186. advérbios compostos ou locuções adverbiais:": "126. advérbios compostos ou locuções adverbiais:",

    "82. todas as preposições simples:": "127. todas as preposições simples:",
    "83. locuções prepositivas:": "128. locuções prepositivas:",
    "84. contrações preposicionais:": "129. contrações preposicionais:",
    "85. regência/preposição não padrão ou variável:": "130. regência/preposição não padrão ou variável:",

    "86. conjunções coordenativas aditivas:": "131. conjunções coordenativas aditivas:",
    "87. conjunções coordenativas alternativas:": "132. conjunções coordenativas alternativas:",
    "88. conjunções coordenativas adversativas:": "133. conjunções coordenativas adversativas:",
    "89. conjunções subordinativas causais:": "134. conjunções subordinativas causais:",
    "90. conjunções subordinativas condicionais:": "135. conjunções subordinativas condicionais:",
    "91. conjunções subordinativas concessivas:": "136. conjunções subordinativas concessivas:",
    "92. conjunções subordinativas temporais:": "137. conjunções subordinativas temporais:",
    "93. conjunções subordinativas consecutivas:": "138. conjunções subordinativas consecutivas:",
    "94. conjunções subordinativas finais:": "139. conjunções subordinativas finais:",
    "95. conjunções subordinativas comparativas:": "140. conjunções subordinativas comparativas:",
    "96. conjunções subordinativas integrantes:": "141. conjunções subordinativas integrantes:",
    "187. conjunções coordenativas conclusivas:": "142. conjunções coordenativas conclusivas:",
    "188. coordenação frasal:": "143. coordenação frasal:",
    "189. coordenação oracional:": "144. coordenação oracional:",
    "190. conjunções subordinativas conformativas:": "145. conjunções subordinativas conformativas:",
    "191. conjunções subordinativas proporcionais:": "146. conjunções subordinativas proporcionais:",

    "97. orações relativas:": "147. orações relativas:",
    "98. orações completivas com que:": "148. orações completivas com que:",
    "99. orações interrogativas indiretas:": "149. orações interrogativas indiretas:",
    "100. orações de infinitivo:": "150. orações de infinitivo:",
    "101. orações de gerúndio:": "151. orações de gerúndio:",
    "102. orações de particípio:": "152. orações de particípio:",
    "103. orações sem verbo/elípticas:": "153. orações sem verbo/elípticas:",
    "104. elipse de sujeito/pro-drop:": "154. elipse de sujeito/pro-drop:",
    "105. elipse de outros constituintes:": "155. elipse de outros constituintes:",
    "106. construções com se:": "156. construções com se:",
    "107. construções de tópico-comentário/deslocamento à esquerda:": "157. construções de tópico-comentário/deslocamento à esquerda:",
    "108. construções relativas resumptivas:": "158. construções relativas resumptivas:",
    "109. ordem não canônica de constituintes:": "159. ordem não canônica de constituintes:",
    "192. interrogativas diretas com elemento interrogativo:": "160. interrogativas diretas com elemento interrogativo:",
    "193. interrogativas diretas sem elemento interrogativo/polares:": "161. interrogativas diretas sem elemento interrogativo/polares:",
    "194. orações relativas com lacuna de sujeito:": "162. orações relativas com lacuna de sujeito:",
    "195. orações relativas com lacuna de objeto:": "163. orações relativas com lacuna de objeto:",
    "196. orações relativas com preposição deslocada ou omitida:": "164. orações relativas com preposição deslocada ou omitida:",
    "197. orações reduzidas de particípio pós-nominais:": "165. orações reduzidas de particípio pós-nominais:",
    "198. apagamento de `que` em completivas:": "166. apagamento de `que` em completivas:",

    "199. orações completivas com `que` controladas por verbo dicendi/comunicação:": "167. orações completivas com `que` controladas por verbo dicendi/comunicação:",
    "200. orações completivas com `que` controladas por verbo cognitivo/mental:": "168. orações completivas com `que` controladas por verbo cognitivo/mental:",
    "201. orações completivas com `que` controladas por verbo de desejo/volição:": "169. orações completivas com `que` controladas por verbo de desejo/volição:",
    "202. orações completivas com `que` controladas por verbo de probabilidade/aparência:": "170. orações completivas com `que` controladas por verbo de probabilidade/aparência:",
    "203. orações completivas com `que` controladas por adjetivo avaliativo:": "171. orações completivas com `que` controladas por adjetivo avaliativo:",
    "204. orações completivas com `que` controladas por adjetivo de certeza:": "172. orações completivas com `que` controladas por adjetivo de certeza:",
    "205. orações completivas com `que` controladas por adjetivo de probabilidade:": "173. orações completivas com `que` controladas por adjetivo de probabilidade:",
    "206. orações completivas com `que` controladas por substantivo factual:": "174. orações completivas com `que` controladas por substantivo factual:",
    "207. orações completivas com `que` controladas por substantivo não factual:": "175. orações completivas com `que` controladas por substantivo não factual:",
    "208. orações completivas com `que` controladas por substantivo de atitude:": "176. orações completivas com `que` controladas por substantivo de atitude:",
    "209. orações completivas com `que` controladas por substantivo de probabilidade:": "177. orações completivas com `que` controladas por substantivo de probabilidade:",
    "210. orações completivas com `que` no indicativo:": "178. orações completivas com `que` no indicativo:",
    "211. orações completivas com `que` no subjuntivo:": "179. orações completivas com `que` no subjuntivo:",
    "212. orações completivas com `que` controladas por advérbio ou expressão adverbial:": "180. orações completivas com `que` controladas por advérbio ou expressão adverbial:",
    "213. orações completivas com `que` controladas por preposição ou locução prepositiva:": "181. orações completivas com `que` controladas por preposição ou locução prepositiva:",
    "214. infinitivo controlado por verbo de desejo/volição:": "182. infinitivo controlado por verbo de desejo/volição:",
    "215. infinitivo controlado por verbo cognitivo/mental:": "183. infinitivo controlado por verbo cognitivo/mental:",
    "216. infinitivo controlado por verbo causativo:": "184. infinitivo controlado por verbo causativo:",
    "217. infinitivo controlado por verbo modal ou semimodal:": "185. infinitivo controlado por verbo modal ou semimodal:",
    "218. infinitivo controlado por verbo de probabilidade/aparência:": "186. infinitivo controlado por verbo de probabilidade/aparência:",
    "219. infinitivo controlado por adjetivo avaliativo:": "187. infinitivo controlado por adjetivo avaliativo:",
    "220. infinitivo controlado por adjetivo de facilidade/dificuldade:": "188. infinitivo controlado por adjetivo de facilidade/dificuldade:",
    "221. infinitivo controlado por adjetivo de certeza/probabilidade:": "189. infinitivo controlado por adjetivo de certeza/probabilidade:",
    "222. infinitivo controlado por adjetivo atitudinal ou afetivo:": "190. infinitivo controlado por adjetivo atitudinal ou afetivo:",
    "223. infinitivo controlado por substantivo:": "191. infinitivo controlado por substantivo:",
    "224. infinitivo introduzido por preposição:": "192. infinitivo introduzido por preposição:",
    "225. infinitivo controlado por substantivo factual ou não factual:": "193. infinitivo controlado por substantivo factual ou não factual:",
    "226. infinitivo controlado por substantivo de atitude:": "194. infinitivo controlado por substantivo de atitude:",

    "110. próclise:": "195. próclise:",
    "111. ênclise:": "196. ênclise:",
    "112. mesóclise:": "197. mesóclise:",
    "113. próclise em início de frase:": "198. próclise em início de frase:",
    "114. alternância entre clítico e pronome pleno:": "199. alternância entre clítico e pronome pleno:",
    "115. contrações com pronomes clíticos:": "200. contrações com pronomes clíticos:",

    "116. marcadores de abertura:": "201. marcadores de abertura:",
    "117. marcadores de reformulação:": "202. marcadores de reformulação:",
    "118. marcadores de consequência:": "203. marcadores de consequência:",
    "119. marcadores de acordo/confirmação:": "204. marcadores de acordo/confirmação:",
    "120. marcadores apelativos:": "205. marcadores apelativos:",
    "121. marcadores de fechamento:": "206. marcadores de fechamento:",
    "122. partículas discursivas/conversacionais:": "207. partículas discursivas/conversacionais:",

    "123. interjeições:": "208. interjeições:",
    "124. vocativos:": "209. vocativos:",
    "125. muletilhas:": "210. muletilhas:",
    "126. hesitações:": "211. hesitações:",
    "127. repetições:": "212. repetições:",
    "128. reformulações:": "213. reformulações:",
    "129. risos:": "214. risos:",
    "130. sobreposições/interrupções:": "215. sobreposições/interrupções:",
    "131. perguntas de confirmação:": "216. perguntas de confirmação:",

    "132. formas reduzidas e abreviações comuns:": "217. formas reduzidas e abreviações comuns:",
    "133. grafias expressivas ou alongadas:": "218. grafias expressivas ou alongadas:",
    "134. gírias e expressões avaliativas:": "219. gírias e expressões avaliativas:",
    "135. empréstimos e termos de redes sociais:": "220. empréstimos e termos de redes sociais:",
    "136. expressões avaliativas recentes:": "221. expressões avaliativas recentes:",
    "137. hashtags e marcadores de tópico digital:": "222. hashtags e marcadores de tópico digital:",
    "138. emojis e emoticons com função discursiva ou avaliativa:": "223. emojis e emoticons com função discursiva ou avaliativa:",
    "139. sufixos e formações produtivas digitais:": "224. sufixos e formações produtivas digitais:",
    "140. alternância de código:": "225. alternância de código:",
    "141. marcadores de oralidade em escrita digital:": "226. marcadores de oralidade em escrita digital:",
}

text = path.read_text(encoding="utf-8")

for old, new in replacements.items():
    text = text.replace(old, new, 1)

path.write_text(text, encoding="utf-8")
print("Sequência numérica corrigida.")